### ISSUE TITLE
Remove MunkiCatalogBuilder processor steps from recipes

### ISSUE THREAD

**Issue by gregneagle** [autopkg/vmule-recipes#4]
The [AdobeFlashDebuggerExtractPackage.munki.recipe](https://github.com/autopkg/vmule-recipes/blob/master/AdobeFlashDebugger/AdobeFlashDebuggerExtractPackage.munki.recipe) and https://github.com/autopkg/vmule-recipes/blob/master/AdobeFlashPlayer/AdobeFlashPlayerExtractPackage.munki.recipe recipes each contain a step using an old, abandoned processor: MunkiCatalogBuilder.

A future release of AutoPkg will cause that Processor to emit a warning about its deprecation, and it will do nothing. A further future release will remove it entirely.

You _could_ modify the recipes to remove the use of that processor, or, since Adobe Flash has been dead for a while, you could just remove those recipes entirely. Your call, and this is why I did not create a pull request.

**Comment by vmule** [comment]
Feel free to archive this repo, I don't think it's being used by anyone anymore.
Cheers

**Comment by homebysix** [comment]
I'll handle the archival. Thanks for letting us know.

Follow up issue for tracking: https://github.com/autopkg/autopkg/issues/912
